# Generated by Django 4.1.5 on 2023-03-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=300)),
                ('employeesid', models.IntegerField()),
                ('teacheremail', models.CharField(max_length=200)),
                ('teacherpassword', models.CharField(max_length=300)),
                ('teachermobile', models.IntegerField()),
                ('joindate', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('workexp', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='Teacher/')),
                ('gender', models.CharField(choices=[{'Male', 'M'}, {'F', 'Female'}, {'O', 'Other'}], max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('teachercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=100)),
                ('smobile', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=255)),
                ('scollege', models.CharField(max_length=255)),
                ('sdegree', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('due_amount', models.FloatField()),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
